[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["dependencies"]
name = "Unit3Dup-AST"
version = "1.0"
description = "Custom Unit3D uploader for Arabic Source Team (AST)"
readme = "README.rst"
requires-python = ">=3.10"
license = "MIT"

authors = [
    { name = "harment" }
]

[project.urls]
Homepage = "https://github.com/harment/Unit3Dup-AST"


[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests", "docs", "http_cache", "venv*"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }


[project.scripts]
unit3dup = "unit3dup.__main__:main"


